export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COIN_SUCCESS ='LOAD_COIN_SUCCESS';
export const LOAD_NOMINAL_SUCCESS ='LOAD_NOMINAL_SUCCESS';

export const CREATE_COIN_SUCCESS = 'CREATE_COIN_SUCCESS';
export const UPDATE_COIN_SUCCESS = 'UPDATE_COIN_SUCCESS';
