export const LOAD_COIN_SUCCESS ='LOAD_COIN_SUCCESS';
export const LOAD_NOMINAL_SUCCESS ='LOAD_NOMINAL_SUCCESS';

export const CREATE_COIN_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COIN_SUCCESS = 'UPDATE_COURSE_SUCCESS';
